### ISSUE TITLE
Configure rules per dependency / language

### ISSUE THREAD

**Issue by AlistairB** [deadpendency/deadpendency#25]
Related to #21 .

## Why?

Each dependency is different and you may want to apply different rules to certain dependencies. For highly active dependencies, you may want stricter checks. Or for low activity dependencies you may want to disable the recent commit check, but still know if the dependency is deprecated.

## Acceptance Criteria

```yaml
# rough sketch for now
rules-config:
  overrides:
    javascript:
        single-author-rule: false
     specific-dep:
       react:
         no-recent-package-release:
           warn-at-months: 6
```
