### ISSUE TITLE
Support ignoring dependencies per language

### ISSUE THREAD

**Issue by AlistairB** [deadpendency/deadpendency#26]
## Why?

#22 breaks down the report by programming language, but currently it is tricky to break down the ignore section by programming language. Deadpendency could look at what dep file the ignored deps come from, then use that information. However, really ignored deps should already be specific to a language. For example you may want to ignore a dep `request` in javascript, but then use a dep `request` in Haskell. Currently you either ignore for all languages, or allow for all.

## Acceptance Criteria

- Support the following:

```yaml
ignore-failures:
  javascript:
    - this-is-js-dep
    - other-languages-can-use-this-dep-name
```

- global ignores will no longer be supported. There is no reason to want to ignore the same dep name in many languages.
