### ISSUE TITLE
Adding a repository for a package with an unknown repository does not remove it from the "Failed to analyze" list

### ISSUE THREAD

**Issue by fniessink** [deadpendency/deadpendency#34]
I have a few packages that deadpendency fails to find the GitHub repo for, e.g. bandit. I would expect that adding:

```yaml
additional-deps:
  python:
    - name: bandit
      repo: PyCQA/bandit
```
would remove bandit from the list of "Failed to analyze" packages, but it doesn't.
