### ISSUE TITLE
Support globbing in additional dependency files

### ISSUE THREAD

**Issue by AlistairB** [deadpendency/deadpendency#53]
## Why do you want this feature?
If there are many additional dependency files, it is cumbersome to specify them all. Globbing is a nice way to target multiple at once with something like:

```yaml
additional-dependency-files:
  - type: pip-requirements-txt
    path: ./requirements/**/*.txt
```

Relates to https://github.com/deadpendency/deadpendency/issues/52

## Acceptance Critera
- Support globbing in `additional-dependency-files` path.
